version: '3'
services:
  db:
    image: mysql:8.0
    container_name: mysql_db

    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci

    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_NAME:-mydb}
      MYSQL_USER: ${DB_USER:-user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - ./src/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro